version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  
  pre_build:   
    commands:
      - echo installing source npm depedencies
      - npm i -g npm-upgrade
      - npm install -g @angular/cli

  build:
    commands:
      - ng build -c --prod

artifacts:
  files:
    - 'dist/*'
  discard-paths: yes
  base-directory: '.'