version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  
  pre_build:   
    commands:
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - ng build

artifacts:
  files:
    - 'dist/*'
  discard-paths: yes
  base-directory: '.'