version: 0.2

phases:
  install:
    commands:
     curl -sL https://deb.nodesource.com/setup_16.x | bash -
     apt-get install -y nodejs
  
  pre_build:   
    commands:
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - ng build

artifacts:
  files:
    - 'dist/*'
  discard-paths: yes
  base-directory: '.'